// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxPZ_ANs9j7ZoQcev5kGME0VabgYbW-0',
    appId: '1:53886720426:web:ff726133088d663b3df3d3',
    messagingSenderId: '53886720426',
    projectId: 'custom-dashboard-82cef',
    authDomain: 'custom-dashboard-82cef.firebaseapp.com',
    storageBucket: 'custom-dashboard-82cef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZke1nkouXE48RHW4XAsKwNx5cBFVL6_g',
    appId: '1:53886720426:android:f644fee17d1f9b113df3d3',
    messagingSenderId: '53886720426',
    projectId: 'custom-dashboard-82cef',
    storageBucket: 'custom-dashboard-82cef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpc14EDrQ7FkHM6I8DxIl1fARR6YrCbc',
    appId: '1:53886720426:ios:9a6a63c695cf39333df3d3',
    messagingSenderId: '53886720426',
    projectId: 'custom-dashboard-82cef',
    storageBucket: 'custom-dashboard-82cef.firebasestorage.app',
    iosBundleId: 'com.example.customDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWpc14EDrQ7FkHM6I8DxIl1fARR6YrCbc',
    appId: '1:53886720426:ios:9a6a63c695cf39333df3d3',
    messagingSenderId: '53886720426',
    projectId: 'custom-dashboard-82cef',
    storageBucket: 'custom-dashboard-82cef.firebasestorage.app',
    iosBundleId: 'com.example.customDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCxPZ_ANs9j7ZoQcev5kGME0VabgYbW-0',
    appId: '1:53886720426:web:bcb3bff3798622753df3d3',
    messagingSenderId: '53886720426',
    projectId: 'custom-dashboard-82cef',
    authDomain: 'custom-dashboard-82cef.firebaseapp.com',
    storageBucket: 'custom-dashboard-82cef.firebasestorage.app',
  );
}
